server:
  port: 9527

spring:
  application:
    name: gp-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # 配置student-service服务
        - id: stu_route
          uri: lb://gp-test-student-service
          predicates:
            - Path=/api/student/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # 配置teacher-service服务
        - id: teacher_route
          uri: lb://gp-test-student-service
          predicates:
            - Path=/api/teacher/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # 配置topic-service服务
        - id: topic_route
          uri: lb://gp-test-student-service
          predicates:
            - Path=/api/topic/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # 配置report-service服务
        - id: report_route
          uri: lb://gp-test-student-service
          predicates:
            - Path=/api/report/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # 配置result-service服务
        - id: result_route
          uri: lb://gp-test-student-service
          predicates:
            - Path=/api/result/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # 配置director-service服务
        - id: result_route
          uri: lb://gp-test-student-service
          predicates:
            - Path=/api/director/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8080/renren-fast          #匹配后提供服务的路由地址
          uri: lb://renren-fast #匹配后提供服务的路由地址
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}




